In [ ]:
# ufc complete dataset에서 체급별 선수 수 파악하는 코드
# fighter_stats.csv 파일의 weight 컬럼 사용

In [ ]:
# UFC 체급 표
# ------------------------------------------------
# strawweight <= 52.3kg
# 52.3kg < flyweight <= 56.7kg
# 56.7kg < bantamweight <= 61.2kg
# 61.2kg < featherweight <= 65.8kg
# 65.8kg < lightweight <= 70.3kg
# 70.3kg < welterweight <= 77.1kg
# 77.1kg < middleweight <= 83.9kg
# 83.9kg < light heavyweight <= 93.0kg
# 93.0kg < heavyweight <= 120.2kg
# -------------------------------------------------

In [1]:
import pandas as pd

In [2]:
# 파일 로드
file_path = 'fighter_stats.csv'  # 파일 경로
data = pd.read_csv(file_path)

In [7]:
data.head(10)

,name,wins,losses,height,weight,reach,age,SLpM,sig_str_acc,SApM,str_def,td_avg,td_acc,td_def,sub_avg,stance_Orthodox,stance_Southpaw,stance_Switch,stance_Sideways,stance_Open Stance
0,Amanda Ribas,12.0,5.0,160.02,56.7,167.64,30.0,4.63,0.4,3.4,0.61,2.07,0.51,0.85,0.7,0,1,0,0,0
1,Rose Namajunas,13.0,6.0,165.1,56.7,165.1,31.0,3.69,0.41,3.51,0.63,1.38,0.47,0.59,0.5,0,1,0,0,0
2,Karl Williams,10.0,1.0,190.5,106.59,200.66,34.0,2.87,0.52,1.7,0.6,4.75,0.5,1.0,0.2,0,1,0,0,0
3,Justin Tafa,7.0,4.0,182.88,119.75,187.96,30.0,4.09,0.54,5.02,0.47,0.0,0.0,0.5,0.0,0,0,0,1,0
4,Edmen Shahbazyan,13.0,4.0,187.96,83.91,190.5,26.0,3.6,0.52,4.09,0.45,2.24,0.38,0.63,0.6,0,1,0,0,0
5,AJ Dobson,7.0,3.0,185.42,83.91,193.04,32.0,4.29,0.46,5.31,0.46,1.67,0.75,0.65,0.3,0,1,0,0,0
6,Payton Talbott,8.0,0.0,177.8,61.23,177.8,25.0,8.05,0.54,3.58,0.51,0.0,0.0,0.9,0.5,0,0,0,0,1
7,Cameron Saaiman,9.0,2.0,172.72,61.23,170.18,23.0,5.32,0.46,4.18,0.51,0.91,0.28,0.47,0.7,0,0,0,1,0
8,Billy Quarantillo,18.0,6.0,177.8,65.77,177.8,35.0,7.36,0.56,5.57,0.43,1.24,0.23,0.61,1.1,0,1,0,0,0
9,Youssef Zalal,14.0,5.0,177.8,65.77,182.88,27.0,2.88,0.49,1.73,0.65,2.28,0.34,0.6,1.3,0,0,0,0,1

In [8]:
# weight 열에서 숫자가 아닌 값을 가진 데이터 필터링
non_numeric_weights = data[~data['weight'].str.replace('.', '', 1).str.isdigit()]

# 출력
print("weight 열에 숫자가 아닌 값을 가진 데이터:")
print(non_numeric_weights)

weight 열에 숫자가 아닌 값을 가진 데이터:
      name  wins  losses  height  weight  reach  age  SLpM  sig_str_acc  SApM  \
2478  name  wins  losses  height  weight  reach  age  SLpM  sig_str_acc  SApM

      str_def  td_avg  td_acc  td_def  sub_avg     stance_Orthodox  \
2478  str_def  td_avg  td_acc  td_def  sub_avg  stance_Open Stance

      stance_Southpaw    stance_Switch  stance_Sideways stance_Open Stance
2478  stance_Orthodox  stance_Sideways  stance_Southpaw      stance_Switch

In [9]:
# 2470번 행부터 2480번 행까지 데이터 확인
subset_data = data.loc[2470:2480]

# 확인 출력
print(subset_data)

                    name  wins  losses  height  weight   reach    age  SLpM  \
2470         Scott Baker   1.0     1.0  182.88   95.25  182.04  37.73   0.0
2471  Alberta Cerra Leon   0.0     1.0  172.72  107.95  182.04  37.73   0.0
2472    Robert Lucarelli   0.0     1.0  187.96  111.13  182.04  37.73   0.0
2473       Frank Hamaker   1.0     0.0  187.96  111.13  182.04  37.73   0.0
2474     Thaddeus Luster   0.0     1.0   190.5   95.25  182.04  37.73   0.0
2475       David Levicki   1.0     3.0  195.58  124.74  182.04  37.73   0.0
2476          Ray Wizard   0.0     1.0  187.96  102.06  182.04  37.73   0.0
2477      Sean Daugherty   0.0     2.0  182.88   79.38  182.04   48.0   0.0
2478                name  wins  losses  height  weight   reach    age  SLpM
2479        Amanda Ribas  12.0     5.0  160.02    56.7  167.64   30.0  4.63
2480      Rose Namajunas  13.0     6.0   165.1    56.7   165.1   31.0  3.69

      sig_str_acc  SApM  str_def  td_avg  td_acc  td_def  sub_avg  \
2470          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2471          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2472          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2473          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2474          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2475          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2476          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2477          0.0   0.0      0.0     0.0     0.0     0.0      0.0
2478  sig_str_acc  SApM  str_def  td_avg  td_acc  td_def  sub_avg
2479          0.4   3.4     0.61    2.07    0.51    0.85      0.7
2480         0.41  3.51     0.63    1.38    0.47    0.59      0.5

         stance_Orthodox  stance_Southpaw    stance_Switch  stance_Sideways  \
2470                   0                1                0                0
2471                   0                1                0                0
2472                   0                1                0                0
2473                   0                1                0                0
2474                   0                1                0                0
2475                   0                1                0                0
2476                   0                1                0                0
2477                   0                1                0                0
2478  stance_Open Stance  stance_Orthodox  stance_Sideways  stance_Southpaw
2479                   0                1                0                0
2480                   0                1                0                0

     stance_Open Stance
2470                  0
2471                  0
2472                  0
2473                  0
2474                  0
2475                  0
2476                  0
2477                  0
2478      stance_Switch
2479                  0
2480                  0

In [10]:
# 2478번 행 제거
data = data.drop(index=2478)

# 제거 후 데이터프레임 확인
print(data.loc[2470:2480])

                    name  wins losses  height  weight   reach    age  SLpM  \
2470         Scott Baker   1.0    1.0  182.88   95.25  182.04  37.73   0.0
2471  Alberta Cerra Leon   0.0    1.0  172.72  107.95  182.04  37.73   0.0
2472    Robert Lucarelli   0.0    1.0  187.96  111.13  182.04  37.73   0.0
2473       Frank Hamaker   1.0    0.0  187.96  111.13  182.04  37.73   0.0
2474     Thaddeus Luster   0.0    1.0   190.5   95.25  182.04  37.73   0.0
2475       David Levicki   1.0    3.0  195.58  124.74  182.04  37.73   0.0
2476          Ray Wizard   0.0    1.0  187.96  102.06  182.04  37.73   0.0
2477      Sean Daugherty   0.0    2.0  182.88   79.38  182.04   48.0   0.0
2479        Amanda Ribas  12.0    5.0  160.02    56.7  167.64   30.0  4.63
2480      Rose Namajunas  13.0    6.0   165.1    56.7   165.1   31.0  3.69

     sig_str_acc  SApM str_def td_avg td_acc td_def sub_avg stance_Orthodox  \
2470         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2471         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2472         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2473         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2474         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2475         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2476         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2477         0.0   0.0     0.0    0.0    0.0    0.0     0.0               0
2479         0.4   3.4    0.61   2.07   0.51   0.85     0.7               0
2480        0.41  3.51    0.63   1.38   0.47   0.59     0.5               0

     stance_Southpaw stance_Switch stance_Sideways stance_Open Stance
2470               1             0               0                  0
2471               1             0               0                  0
2472               1             0               0                  0
2473               1             0               0                  0
2474               1             0               0                  0
2475               1             0               0                  0
2476               1             0               0                  0
2477               1             0               0                  0
2479               1             0               0                  0
2480               1             0               0                  0

In [12]:
# weight 열에서 숫자가 아닌 값을 가진 데이터 필터링
non_numeric_weights = data[~data['weight'].str.replace('.', '', 1).str.isdigit()]

# 출력
print("weight 열에 숫자가 아닌 값을 가진 데이터:")
print(non_numeric_weights)

weight 열에 숫자가 아닌 값을 가진 데이터:
Empty DataFrame
Columns: [name, wins, losses, height, weight, reach, age, SLpM, sig_str_acc, SApM, str_def, td_avg, td_acc, td_def, sub_avg, stance_Orthodox, stance_Southpaw, stance_Switch, stance_Sideways, stance_Open Stance]
Index: []

In [13]:
# 숫자로 변환할 수 없는 데이터 확인
non_numeric_weights = data[~data['weight'].apply(lambda x: isinstance(x, (int, float)) or str(x).replace('.', '', 1).isdigit())]
print("Non-numeric weights data:")
print(non_numeric_weights)

Non-numeric weights data:
Empty DataFrame
Columns: [name, wins, losses, height, weight, reach, age, SLpM, sig_str_acc, SApM, str_def, td_avg, td_acc, td_def, sub_avg, stance_Orthodox, stance_Southpaw, stance_Switch, stance_Sideways, stance_Open Stance]
Index: []

In [17]:
# weight 열을 숫자로 변환 (변환 불가능한 값은 NaN 처리)
data['weight'] = pd.to_numeric(data['weight'], errors='coerce')

In [14]:
# 체급 기준에 따라 체급 분류
def categorize_weight(weight):
    if weight <= 52.3:
        return 'Strawweight'
    elif weight <= 56.7:
        return 'Flyweight'
    elif weight <= 61.2:
        return 'Bantamweight'
    elif weight <= 65.8:
        return 'Featherweight'
    elif weight <= 70.3:
        return 'Lightweight'
    elif weight <= 77.1:
        return 'Welterweight'
    elif weight <= 83.9:
        return 'Middleweight'
    elif weight <= 93.0:
        return 'Light Heavyweight'
    elif weight <= 120.2:
        return 'Heavyweight'
    else:
        return 'Unknown'  # 체급 범위를 벗어난 경우

In [18]:
# 체급 컬럼 생성
data['Weight Class'] = data['weight'].apply(categorize_weight)

In [19]:
# 체급별 선수 수 계산
weight_class_counts = data['Weight Class'].value_counts()

In [20]:
# 출력
print("체급별 선수 수:")
print(weight_class_counts)

체급별 선수 수:
Weight Class
Featherweight        1082
Light Heavyweight    1082
Middleweight          852
Welterweight          806
Heavyweight           510
Flyweight             396
Strawweight           186
Unknown                42
Name: count, dtype: int64

In [21]:
# 체급이 'Unknown'인 선수들의 이름 확인
unknown_fighters = data[data['Weight Class'] == 'Unknown']['name']

# 결과 출력
print("Unknown 체급에 포함된 선수들:")
print(unknown_fighters)

Unknown 체급에 포함된 선수들:
2298          Tedd Williams
2309           Ron Waterman
2333          Andre Roberts
2339            Chris Condo
2360        Harry Moskowitz
2370              Mark Kerr
2377             Dan Bobish
2385          Steven Graham
2386             Tony Halme
2393         Scott Ferrozzo
2405          Paul Varelans
2414         Julian Sanchez
2416             Sam Fulton
2422             Koji Kitao
2428         Thomas Ramirez
2439           Gerry Harris
2447             John Matua
2452               Jon Hess
2461           Kevin Rosier
2464    Emmanuel Yarborough
2475          David Levicki
4777          Tedd Williams
4788           Ron Waterman
4812          Andre Roberts
4818            Chris Condo
4839        Harry Moskowitz
4849              Mark Kerr
4856             Dan Bobish
4864          Steven Graham
4865             Tony Halme
4872         Scott Ferrozzo
4884          Paul Varelans
4893         Julian Sanchez
4895             Sam Fulton
4901             Koji Kitao
4907         Thomas Ramirez
4918           Gerry Harris
4926             John Matua
4931               Jon Hess
4940           Kevin Rosier
4943    Emmanuel Yarborough
4954          David Levicki
Name: name, dtype: object

In [ ]:
# unknown에 포함된 선수들은 어떤 선수들인가?
# Emmanuel Yarborough ~ Mark Kerr 조사결과, 00년대 이전의 ufc 선수들
# 300kg가 넘어가는 사람도 있었다.
# 체급이란 개념이 정리되기 이전의 선수들인 것 같아 제외하기로 함

In [22]:
# Unknown 체급 데이터 제거
data = data[data['Weight Class'] != 'Unknown']

# 결과 확인
print("Unknown 체급이 제거된 데이터셋입니다.")
print(data['Weight Class'].value_counts())

Unknown 체급이 제거된 데이터셋입니다.
Weight Class
Light Heavyweight    1082
Featherweight        1082
Middleweight          852
Welterweight          806
Heavyweight           510
Flyweight             396
Strawweight           186
Name: count, dtype: int64

In [ ]:
# 궁금해서 추가로 찾아보니
# ufc는 1993 무차별 토너먼트로 시작
# 1996 체급 도입
# 1997 체급별 타이틀 진행
# 00년 이전에는 체급 분리의 개념 없이 싸웠다고 봐도 무방..
# 따라서 00년 이전 데이터는 제거하기로 함.
# 하지만 fighter_stats에는 관련 특성이 없음.
# 이 처리는 추후 하는 것으로..

In [ ]:
# 문제발생!!!
# 선수정보의 체급에 밴텀급이 하나도 없어 살펴보니,
# 션 오말리 등 최근에 경기를 한 선수들도 없었다.
# large_dataset에는 포함되어 있는 선수지만,
# fighter_stats에는 없는 것.
# large_dataset의 선수와 fighter_stats의 선수가 일치한다고 생각하면 안될 것 같다.